version: 2.1

orbs:
  gpo: fernfernfern/github-pages-orb@0.0.8

workflows:
  test-deploy:
    jobs:
      - gpo/test:
          with-gems: true
          filters:
            branches:
              ignore:
                - gh-pages
      - gpo/deploy:
          requires:
            - gpo/test
          filters:
            branches:
              only:
                - master
